[project]
name = 'bitcoin-savings-account'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.rewards]
path = 'contracts/rewards.clar'
clarity_version = 3
epoch = 3.0

[contracts.savings-account]
path = 'contracts/savings-account.clar'
clarity_version = 3
epoch = 3.0

[contracts.savings-interface]
path = 'contracts/savings-interface.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
